FROM opensuse/leap:42.3

# For CPU2006
RUN zypper --non-interactive install \
    gcc \
    gcc-c++ \
    gcc-fortran \
    gdb \
    git

# Helper utilities
RUN zypper --non-interactive install \
    vim

WORKDIR /opt/speccpu

ENTRYPOINT ["/bin/bash"]
