version: "3.5"
services:
  # ***** SNIPER SERVICE *****
  sniper:
    build:
      dockerfile: ./src/dockerfiles/Dockerfile-sniper
      context: .
    image: nvmsim/sniper:latest
    container_name: sniper
    environment:
      SNIPER_TARGET_ARCH: ${SNIPER_TARGET_ARCH}
    # restart: always
    privileged: true
    volumes:
      - ./shared/sniper:/opt/sniper
      - ./shared/pinplay:/opt/pinplay
      - ./src/entrypoints/entrypoint-sniper.sh:/usr/local/bin/entrypoint.sh
      - ./shared/nvmsim:/mnt/nvmsim
    networks:
      - nvmsim-network
    ports:
      - "7200:7200"
    command:
      - entrypoint.sh
  # ***** NVMAIN SERVICE *****
  nvmain:
    build:
      dockerfile: ./src/dockerfiles/Dockerfile-nvmain
      context: .
    image: nvmsim/nvmain:latest
    container_name: nvmain
    # restart: always
    privileged: true
    volumes:
      - ./shared/nvmain:/opt/nvmain
      - ./src/entrypoints/entrypoint-nvmain.sh:/usr/local/bin/entrypoint.sh
      - ./shared/nvmsim:/mnt/nvmsim
    depends_on:
      - sniper
    networks:
      - nvmsim-network
    ports:
      - "2000:2000"
    command:
      - entrypoint.sh
networks:
  nvmsim-network:
    driver: bridge
