version: "3"
services:
  # ***** SNIPER SERVICE *****
  sniper:
    build:
      dockerfile: ./src/sniper/Dockerfile
      context: .
    image: nvmsim/sniper:latest
    container_name: sniper
    # restart: always
    privileged: true
    volumes:
      - ./src/sniper/entrypoint.sh:/usr/local/bin/entrypoint.sh
      - ./shared/logs:/nvmsim/logs
      - ./shared:/mnt/shared
    networks:
      - nvmsim-network
    ports:
      - "7200:7200"
    command:
      - entrypoint.sh
  # ***** NVMAIN SERVICE *****
  nvmain:
    build:
      dockerfile: ./src/nvmain/Dockerfile
      context: .
    image: nvmsim/nvmain:latest
    container_name: nvmain
    # restart: always
    volumes:
      - ./src/nvmain/entrypoint.sh:/usr/local/bin/entrypoint.sh
      - ./src/nvmain/tracefile.nvt:/opt/nvmain/tracefile.nvt
      - ./shared:/mnt/shared
    depends_on:
      - sniper
    networks:
      - nvmsim-network
    ports:
      - "2000:2000"
    command:
      - entrypoint.sh
networks:
  nvmsim-network:
    driver: bridge
