version: "3"
services:
  sniper:
    build:
      dockerfile: ./src/sniper/Dockerfile
      context: .
    image: nvmsim/sniper:latest
    container_name: sniper
    restart: always
    privileged: true
    volumes:
      - ./src/sniper/entrypoint.sh:/usr/local/bin/entrypoint.sh
      - ./shared/logs:/nvmsim/logs
    networks:
      - nvmsim-network
    ports:
      - "7200:7200"
    depends_on:
      - nvmain
    links: 
      - nvmain
    command:
      - entrypoint.sh

  nvmain:
    build:
      dockerfile: ./src/nvmain/Dockerfile
      context: .
    image: nvmsim/nvmain:latest
    container_name: nvmain
    restart: always
    volumes:
      - ./src/nvmain/entrypoint.sh:/usr/local/bin/entrypoint.sh
      - ./src/nvmain/tracefile.nvt:/opt/nvmain/tracefile.nvt
    networks:
      - nvmsim-network
    ports:
      - "2000:2000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2000"]
      interval: 30s
      timeout: 10s
      retries: 5
    command:
      - entrypoint.sh

networks:
  nvmsim-network:
    driver: bridge

