version: "3.5"
services:
  sniper:
    container_name: sniper
    image: nvmsim/sniper:latest
    restart: always
    volumes:
      - ./src/sniper/entrypoint.sh:/usr/local/bin/entrypoint.sh
    command:
      - entrypoint.sh
  nvmain:
    container_name: nvmain
    image: nvmsim/nvmain:latest
    restart: always
    volumes:
      - ./src/nvmain/entrypoint.sh:/usr/local/bin/entrypoint.sh
    command:
      - entrypoint.sh
