version: "3"
services:
  sniper:
    build:
      dockerfile: ./src/sniper/Dockerfile
      context: .
    image: nvmsim/sniper:latest
    container_name: sniper
#    restart: always
    privileged: true
    volumes:
      - ./src/sniper/entrypoint.sh:/usr/local/bin/entrypoint.sh
      - ./shared/logs:/nvmsim/logs
    networks:
      - nvmsim-network
    ports:
      - "7200:7200"
    command:
      - entrypoint.sh

  nvmain:
    build:
      dockerfile: ./src/nvmain/Dockerfile
      context: .
    image: nvmsim/nvmain:latest
    container_name: nvmain
#    restart: always
    volumes:
      - ./src/nvmain/entrypoint.sh:/usr/local/bin/entrypoint.sh
    networks:
      - nvmsim-network
    ports:
      - "2000:2000"
    depends_on:
      - "sniper"
    command:
      - entrypoint.sh

networks:
  nvmsim-network:
    driver: bridge

