FROM debian:9.4

# Add i386 support for support for Pin
RUN dpkg --add-architecture i386
RUN apt-get update && apt-get install -y \
    python \
    screen \
    tmux \
    binutils \
    libc6:i386 \
    libncurses5:i386 \
    libstdc++6:i386 \
    && rm -rf /var/lib/apt/lists/*

# For building Sniper
RUN apt-get update && apt-get install -y \
    automake \
    build-essential \
    curl \
    wget \
    libboost-dev \
    libsqlite3-dev \
    zlib1g-dev \
    libbz2-dev \
    g++-6 \
    && rm -rf /var/lib/apt/lists/*

# For building RISC-V Tools
RUN apt-get update && apt-get install -y \
    autoconf \
    automake \
    autotools-dev \
    bc \
    bison \
    curl \
    device-tree-compiler \
    flex \
    gawk \
    gperf \
    libexpat1-dev \
    libgmp-dev \
    libmpc-dev \
    libmpfr-dev \
    libtool \
    libusb-1.0-0-dev \
    patchutils \
    pkg-config \
    texinfo \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

# Helper utilities
RUN apt-get update && apt-get install -y \
    gdb \
    git \
    procps \
    vim \
    emacs \
    && rm -rf /var/lib/apt/lists/*

ADD vendor/pin-3.7-97619-g0d0c92f4f-gcc-linux.tar.gz /opt
ENV PIN_HOME=/opt/pin-3.7-97619-g0d0c92f4f-gcc-linux

ADD vendor/sniper-7.1.tgz /opt
ENV SNIPER_HOME=/opt/sniper-7.1

RUN echo 'installing sniper...'
RUN cd /opt/sniper-7.1/; make
RUN echo 'installing sniper... done'

RUN echo "alias run-sniper='/opt/sniper-7.1/run-sniper'" >> ~/.bashrc
RUN echo "alias test-sniper='cd /opt/sniper-7.1/test/fft; make run'" >> ~/.bashrc

WORKDIR /nvmsim

ENTRYPOINT ["/bin/bash"]
