version: "3.5"
services:
  ##### SNIPER SERVICE #####
  sniper:
    build:
      dockerfile: ./src/dockerfiles/Dockerfile-sniper
      context: .
    image: nvmsim/sniper:latest
    environment:
      ENABLE_SNIPER: ${ENABLE_SNIPER}
      SNIPER_TARGET_ARCH: ${SNIPER_TARGET_ARCH}
      SNIPER_MEMORY_TYPE: ${SNIPER_MEMORY_TYPE}
      NVMAIN_CONFIG_FILES: ${NVMAIN_CONFIG_FILES}
      TZ: "America/Sao_Paulo"
    privileged: true
    volumes:
      - ./shared/sniper:/opt/sniper
      - ./shared/pinplay:/opt/pinplay
      - ./src/entrypoints/entrypoint-sniper.sh:/usr/local/bin/entrypoint.sh
      - ./shared/nvmsim:/mnt/nvmsim
    networks:
      - nvmsim-network
    command:
      - entrypoint.sh
  ##### NVMAIN SERVICE #####
  nvmain:
    build:
      dockerfile: ./src/dockerfiles/Dockerfile-nvmain
      context: .
    image: nvmsim/nvmain:latest
    environment:
      ENABLE_NVMAIN: ${ENABLE_NVMAIN}
      NVMAIN_CONFIG_FILES: ${NVMAIN_CONFIG_FILES}
      TZ: "America/Sao_Paulo"
    privileged: true
    volumes:
      - ./shared/nvmain:/opt/nvmain
      - ./src/entrypoints/entrypoint-nvmain.sh:/usr/local/bin/entrypoint.sh
      - ./shared/nvmsim/:/mnt/nvmsim/
    depends_on:
      - sniper
    networks:
      - nvmsim-network
    command:
      - entrypoint.sh
  ##### SPEC CPU SERVICE #####
  speccpu:
    build:
      dockerfile: ./src/dockerfiles/Dockerfile-speccpu
      context: .
    image: nvmsim/speccpu:latest
    container_name: speccpu
    environment:
      ENABLE_SPECCPU: ${ENABLE_SPECCPU}
    privileged: true
    volumes:
      - ./src/entrypoints/entrypoint-speccpu.sh:/usr/local/bin/entrypoint.sh
      - ${SPECCPU_PATH}:/mnt/dvd
      - ./shared/speccpu:/mnt/speccpu
      - ./shared/nvmsim:/mnt/nvmsim
    networks:
      - nvmsim-network
    command:
      - entrypoint.sh
networks:
  nvmsim-network:
    driver: bridge
