FROM ubuntu:18.04

# For NVMain
RUN apt-get update && apt-get install -y \
    build-essential \
    mercurial \
    scons \
    && rm -rf /var/lib/apt/lists/*

# Helper utilities
RUN apt-get update && apt-get install -y \
    dnsutils \
    gdb \
    git \
    net-tools \
    vim \
    && rm -rf /var/lib/apt/lists/*

# Set environment values and alias
ENV NVMSIM="sniper"

WORKDIR /opt/nvmain

ENTRYPOINT ["/bin/bash"]
